In [14]:
import pandas as pd
import numpy as np

In [15]:
dataset = pd.read_csv("condensed_dow_and_sentiment.csv")
dataset

,Unnamed: 0,Time,Vader_compound,High,Low,Tweet_text
0,0,2016-01-20 11:14:50+00:00,0.8012,15989.450195,15450.559570,"""@ron_fournier: President Donald Trump (just g..."
1,1,2016-01-20 11:16:00+00:00,0.7003,15989.450195,15450.559570,"""@nytimes: Breaking News: Sarah Palin has endo..."
2,2,2016-01-20 13:40:29+00:00,0.0000,15989.450195,15450.559570,#MakeAmericaGreatAgain #Trump2016\nLIFE CHANGI...
3,3,2016-01-20 15:53:12+00:00,0.8550,15989.450195,15450.559570,Great rally in Iowa! Such wonderful people. Tr...
4,4,2016-01-20 18:02:58+00:00,0.3612,15989.450195,15450.559570,RT @SarahPalinUSA: Trading in the beautiful sn...
...,...,...,...,...,...,...
25181,25181,2020-08-14 23:41:55+00:00,0.9285,27977.810547,27759.390625,Senator @CoryGardner is doing a terrific job -...
25182,25182,2020-08-14 23:43:03+00:00,0.7257,27977.810547,27759.390625,...Steve Bullock is totally against your Secon...
25183,25183,2020-08-14 23:43:03+00:00,0.4574,27977.810547,27759.390625,Senator @SteveDaines is doing a tremendous job...
25184,25184,2020-08-15 03:59:18+00:00,0.9879,27977.810547,27759.390625,"Today, it was my great honor to proudly accept..."
25185,25185,2020-08-15 04:14:34+00:00,0.9516,27977.810547,27759.390625,We will bring safety to our cities. We will br...

In [16]:
dataset["Tweet_text"] = dataset["Tweet_text"].str.lower()

In [56]:
#use filtered_data for tweets within the desired date range
start_date = '2018-01-01 00:00:00+00:00'
end_date = '2018-12-31 00:00:00+00:00'

begin = dataset["Time"] >= start_date
end = dataset["Time"] <= end_date

between_dates = begin & end
filtered_data = dataset.loc[between_dates]
filtered_data

,Unnamed: 0,Time,Vader_compound,High,Low,Tweet_text
6583,6583,2018-01-01 12:12:00+00:00,-0.8256,24871.660156,24719.220703,the united states has foolishly given pakistan...
6584,6584,2018-01-01 12:44:40+00:00,0.8672,24871.660156,24719.220703,iran is failing at every level despite the ter...
6585,6585,2018-01-01 13:37:52+00:00,0.7871,24871.660156,24719.220703,will be leaving florida for washington (d.c.) ...
6586,6586,2018-01-02 12:09:17+00:00,-0.9414,24864.189453,24741.699219,the people of iran are finally acting against ...
6587,6587,2018-01-02 12:48:00+00:00,0.6312,24864.189453,24741.699219,"crooked hillary clinton’s top aid, huma abedin..."
...,...,...,...,...,...,...
10134,10134,2018-12-30 03:01:28+00:00,0.5255,23381.880859,22981.330078,“absolutely nothing” (on russian collusion). k...
10135,10135,2018-12-30 03:15:36+00:00,-0.2648,23381.880859,22981.330078,"“it turns out to be true now, that the departm..."
10136,10136,2018-12-30 15:28:35+00:00,0.8908,23381.880859,22981.330078,veterans on president trump’s handling of bord...
10137,10137,2018-12-30 16:56:09+00:00,0.9116,23381.880859,22981.330078,great work by my administration over the holid...
10138,10138,2018-12-30 21:59:44+00:00,0.7901,23381.880859,22981.330078,president and mrs. obama built/has a ten foot ...

In [61]:
market_filtered = filtered_data[filtered_data['Tweet_text'].str.contains('market')]
market_filtered

#add a column thats the high minus the low for total variation for the day = volatility

,Unnamed: 0,Time,Vader_compound,High,Low,Tweet_text
6605,6605,2018-01-04 02:11:31+00:00,-0.1386,25105.960938,24963.269531,"stock market had another good day but, now tha..."
6615,6615,2018-01-05 04:04:20+00:00,-0.5696,25299.789063,25112.009766,the fake news media barely mentions the fact t...
6622,6622,2018-01-06 11:57:35+00:00,-0.9318,25299.789063,25112.009766,"brian ross, the reporter who made a fraudulent..."
6630,6630,2018-01-07 20:42:13+00:00,0.9279,25299.789063,25112.009766,the stock market has been creating tremendous ...
6675,6675,2018-01-13 13:13:12+00:00,-0.3382,25810.429688,25633.080078,yesterday was a big day for the stock market. ...
6678,6678,2018-01-13 14:20:00+00:00,-0.4199,25810.429688,25633.080078,yesterday was another big day for jobs and the...
6681,6681,2018-01-14 03:42:07+00:00,0.7777,25810.429688,25633.080078,rt @loudobbs: the stock market has gained an i...
6690,6690,2018-01-14 13:50:14+00:00,0.6144,25810.429688,25633.080078,“president trump is not getting the credit he ...
6743,6743,2018-01-20 22:31:27+00:00,0.0752,26071.720703,25942.830078,"unprecedented success for our country, in so m..."
6819,6819,2018-02-07 14:59:49+00:00,0.9049,25293.960938,24785.439453,"in the “old days,” when good news was reported..."
6950,6950,2018-02-27 18:18:22+00:00,0.8622,25800.349609,25407.830078,“american consumers are the most confident the...
7183,7183,2018-04-08 00:03:23+00:00,0.6588,24434.400391,23738.199219,while security spending was somewhat more than...
7643,7643,2018-05-31 11:53:08+00:00,-0.4767,24620.789063,24352.150391,"iger, where is my call of apology? you and abc..."
7653,7653,2018-06-01 13:18:21+00:00,0.0000,24673.599609,24542.089844,canada has treated our agricultural business a...
7763,7763,2018-06-09 23:03:16+00:00,-0.3080,25325.630859,25165.699219,based on justin’s false statements at his news...
7774,7774,2018-06-11 21:52:36+00:00,-0.8777,25402.830078,25290.199219,"stock market up almost 40% since the election,..."
7976,7976,2018-06-26 11:25:01+00:00,0.5562,24384.210938,24241.220703,....we are getting other countries to reduce a...
8155,8155,2018-07-14 09:46:55+00:00,-0.6588,25043.210938,24890.060547,"the stock market hit 25,000 yesterday. jobs ar..."
8275,8275,2018-07-25 00:08:01+00:00,0.7028,25432.869141,25113.550781,the european union is coming to washington tom...
8428,8428,2018-08-04 19:47:40+00:00,0.6369,25467.900391,25325.169922,tariffs are working far better than anyone eve...
8576,8576,2018-08-17 14:06:13+00:00,0.2479,25728.160156,25521.660156,wow! big pushback on governor andrew cuomo of ...
8577,8577,2018-08-17 14:10:25+00:00,0.2479,25728.160156,25521.660156,wow! big pushback on governor andrew cuomo of ...
8636,8636,2018-08-22 20:07:29+00:00,0.6360,25836.160156,25722.429688,longest bull run in the history of the stock m...
8677,8677,2018-08-25 23:45:48+00:00,0.6360,25826.050781,25688.580078,stock market hit all time high on friday. cong...
8684,8684,2018-08-26 14:31:06+00:00,0.5983,25826.050781,25688.580078,fantastic numbers on consumer spending release...
8737,8737,2018-08-30 11:20:48+00:00,0.7495,26104.369141,25934.800781,the news from the financial markets is even be...
8860,8860,2018-09-09 14:12:18+00:00,-0.3164,26002.990234,25818.390625,“trump has set economic growth on fire. during...
8924,8924,2018-09-13 14:15:55+00:00,-0.6820,26191.640625,26067.080078,"the wall street journal has it wrong, we are u..."
9075,9075,2018-09-22 03:09:25+00:00,0.0000,26769.160156,26680.369141,"rt @foxbusiness: .@potus: ""the stock market is..."
9116,9116,2018-09-26 17:26:54+00:00,-0.4199,26606.089844,26349.339844,china is actually placing propaganda ads in th...
9136,9136,2018-10-01 10:40:24+00:00,0.4389,26737.980469,26596.050781,".....deficiencies and mistakes in nafta, great..."
9137,9137,2018-10-01 10:53:28+00:00,0.4389,26737.980469,26596.050781,"....deficiencies and mistakes in nafta, greatl..."
9159,9159,2018-10-03 13:04:02+00:00,0.1027,26951.810547,26789.080078,the stock market just reached an all-time high...
9163,9163,2018-10-03 14:05:28+00:00,0.0000,26951.810547,26789.080078,"blowout numbers on new jobs and, separately, s..."
9311,9311,2018-10-16 14:12:06+00:00,0.8261,25817.679688,25351.529297,"incredible number just out, 7,036,000 job open..."
9325,9325,2018-10-17 02:39:24+00:00,0.7290,25810.089844,25479.160156,"stock market up 548 points today. also, great ..."
9331,9331,2018-10-17 12:40:15+00:00,0.0000,25810.089844,25479.160156,“network news gave zero coverage to the big da...
9498,9498,2018-10-30 12:33:39+00:00,0.7959,24906.679688,24415.689453,the stock market is up massively since the ele...
9507,9507,2018-10-31 13:04:26+00:00,0.8070,25336.550781,25008.820313,stock market up more than 400 points yesterday...
9608,9608,2018-11-05 21:40:04+00:00,0.8491,25507.349609,25261.470703,republicans have created the best economy in t...
9693,9693,2018-11-12 15:34:09+00:00,-0.3802,25966.710938,25340.509766,the prospect of presidential harassment by the...
10005,10005,2018-12-17 21:14:10+00:00,0.7959,24088.080078,23456.880859,today i am making good on my promise to defend...
10008,10008,2018-12-18 12:13:24+00:00,0.3802,23927.769531,23516.019531,i hope the people over at the fed will read to...
10099,10099,2018-12-24 15:55:22+00:00,0.1007,22339.869141,21792.199219,the only problem our economy has is the fed. t...
10133,10133,2018-12-29 21:06:08+00:00,-0.1027,23381.880859,22981.330078,2018 is being called “the year of the worker” ...

In [17]:
market = dataset[dataset['Tweet_text'].str.contains('market')]
market

,Unnamed: 0,Time,Vader_compound,High,Low,Tweet_text
857,857,2016-03-07 22:48:21+00:00,0.9098,17099.250000,16940.480469,thank you idaho! i love your potatoes- \nnobod...
1920,1920,2016-06-10 02:31:06+00:00,0.5994,17938.820313,17812.339844,"""@freemarketsara: trump's historic 13 million ..."
2079,2079,2016-06-26 22:15:40+00:00,-0.7125,17946.630859,17356.339844,crooked hillary clinton got brexit wrong. i sa...
2092,2092,2016-06-28 19:24:43+00:00,-0.1603,17409.720703,17190.509766,"""@arnold_ziffel: @anncoulter also can't help b..."
2692,2692,2016-08-16 23:17:18+00:00,-0.0516,18614.859375,18550.650391,"just as we won the cold war, in part, by expos..."
...,...,...,...,...,...,...
24624,24624,2020-07-28 02:58:41+00:00,-0.6114,26556.839844,26361.710938,"....would destroy our american cities, and wor..."
24640,24640,2020-07-28 03:22:44+00:00,-0.4404,26556.839844,26361.710938,rt @realdonaldtrump: ....would destroy our ame...
24692,24692,2020-07-29 16:19:56+00:00,-0.1511,26602.449219,26375.390625,...your housing prices will go up based on the...
24759,24759,2020-08-01 21:29:29+00:00,-0.8087,26440.019531,26013.589844,“biden to raise taxes by 3 trillion dollars.” ...
25035,25035,2020-08-11 12:34:14+00:00,0.0000,28154.880859,27624.509766,big stock market numbers!

In [18]:
stock = dataset[dataset['Tweet_text'].str.contains('stock')]
stock

,Unnamed: 0,Time,Vader_compound,High,Low,Tweet_text
1823,1823,2016-06-02 05:11:16+00:00,-0.1002,17838.560547,17703.550781,"""@scpioneer: @stockdaleism @jamesrosenfnc @fox..."
2092,2092,2016-06-28 19:24:43+00:00,-0.1603,17409.720703,17190.509766,"""@arnold_ziffel: @anncoulter also can't help b..."
2978,2978,2016-09-17 21:38:50+00:00,-0.8715,18217.210938,18070.210938,the failing @nytimes has gone nuts that crooke...
4300,4300,2017-02-16 11:34:46+00:00,0.9392,20639.869141,20556.830078,stock market hits new high with longest winnin...
4352,4352,2017-03-02 11:00:41+00:00,0.7734,21129.199219,20996.609375,"since november 8th, election day, the stock ma..."
...,...,...,...,...,...,...
24397,24397,2020-07-21 11:33:05+00:00,0.5983,27025.380859,26766.220703,strong stock market numbers. you want to see t...
24497,24497,2020-07-25 04:21:51+00:00,-0.2960,26625.699219,26402.859375,rt @marketwatch: pharma stocks finish lower as...
24855,24855,2020-08-03 13:49:25+00:00,0.0000,26707.259766,26534.380859,record high nasdaq! it would all come crashing...
24988,24988,2020-08-08 19:28:59+00:00,-0.8283,27456.240234,27223.550781,sleepy joe biden just agreed with the radical ...
25035,25035,2020-08-11 12:34:14+00:00,0.0000,28154.880859,27624.509766,big stock market numbers!

In [42]:
dow = dataset[dataset['Tweet_text'].str.contains('dow')]
dow

,Unnamed: 0,Time,Vader_compound,High,Low,Tweet_text
27,27,2016-01-22 03:56:44+00:00,-0.8777,16136.790039,15921.099609,national review is a failing publication that ...
55,55,2016-01-22 23:58:14+00:00,0.0000,16136.790039,15921.099609,ted cruz went down big in just released reuter...
66,66,2016-01-23 13:35:35+00:00,0.0000,16136.790039,15921.099609,"""@noamscheiber: dow down almost 2000 pts since..."
70,70,2016-01-23 15:07:04+00:00,0.0000,16136.790039,15921.099609,ted cruz poll numbers are down big. because he...
77,77,2016-01-23 20:15:59+00:00,0.0000,16136.790039,15921.099609,"heading now to pella, iowa. big crowd! remembe..."
...,...,...,...,...,...,...
25047,25047,2020-08-12 12:11:05+00:00,-0.8176,28043.890625,27843.320313,watched @billmaher last week for the first tim...
25075,25075,2020-08-13 11:17:17+00:00,-0.8217,27986.099609,27789.779297,the fake news media is giving @kamalaharris a ...
25076,25076,2020-08-13 13:56:53+00:00,-0.8113,27986.099609,27789.779297,"drug companies, which are being forced by me t..."
25094,25094,2020-08-13 23:26:50+00:00,0.9052,27986.099609,27789.779297,.@donyoungak really produces for alaska. he is...
25184,25184,2020-08-15 03:59:18+00:00,0.9879,27977.810547,27759.390625,"today, it was my great honor to proudly accept..."

In [44]:
dow = dataset[dataset['Tweet_text'].str.contains('dow ')]
dow.head()

,Unnamed: 0,Time,Vader_compound,High,Low,Tweet_text
66,66,2016-01-23 13:35:35+00:00,0.0000,16136.790039,15921.099609,"""@noamscheiber: dow down almost 2000 pts since..."
87,87,2016-01-24 09:19:43+00:00,0.0000,16136.790039,15921.099609,"""@noamscheiber: dow down almost 2000 pts since..."
3412,3412,2016-10-19 17:00:22+00:00,0.0000,18252.199219,18169.250000,the state department's 'shadow government' #dr...
4338,4338,2017-02-25 13:27:04+00:00,0.8221,20821.759766,20733.949219,"great optimism for future of u.s. business, an..."
4857,4857,2017-06-11 12:22:20+00:00,-0.2946,21305.349609,21159.449219,the #fakenews msm doesn't report the great eco...

In [36]:
economy = dataset[dataset['Tweet_text'].str.contains('economy')]
economy

,Unnamed: 0,Time,Vader_compound,High,Low,Tweet_text
963,963,2016-03-15 16:16:16+00:00,0.0000,17251.699219,17120.349609,"i will bring our jobs back to the u.s., and ke..."
1132,1132,2016-03-26 19:27:56+00:00,0.7003,17517.140625,17399.009766,wisconsin's economy is doing poorly and like e...
1244,1244,2016-04-08 02:48:30+00:00,0.0000,17694.509766,17528.160156,"""@dicristo13: @realdonaldtrump let's have the ..."
1464,1464,2016-04-30 17:21:35+00:00,0.6037,17814.830078,17651.980469,the economy is bad and getting worse-almost ze...
1641,1641,2016-05-17 14:17:07+00:00,0.4767,17701.460938,17469.919922,crooked hillary said her husband is going to b...
...,...,...,...,...,...,...
24766,24766,2020-08-02 01:27:32+00:00,0.8743,26440.019531,26013.589844,congressman dan newhouse (@newhouse4rep) is do...
24893,24893,2020-08-04 23:00:38+00:00,0.0000,26832.720703,26597.820313,rt @loudobbs: reopening america: president @re...
24979,24979,2020-08-07 22:32:51+00:00,0.1513,27456.240234,27223.550781,i will be doing a news conference on the china...
24988,24988,2020-08-08 19:28:59+00:00,-0.8283,27456.240234,27223.550781,sleepy joe biden just agreed with the radical ...
25013,25013,2020-08-10 17:38:26+00:00,0.9641,27803.859375,27488.210938,congrats to general dynamic’s bath iron works ...

In [38]:
china = dataset[dataset['Tweet_text'].str.contains('china')]
china

,Unnamed: 0,Time,Vader_compound,High,Low,Tweet_text
1541,1541,2016-05-08 20:15:20+00:00,-0.5848,17744.539063,17580.380859,crooked hillary just can't close the deal with...
1599,1599,2016-05-14 01:03:02+00:00,-0.3400,17734.740234,17512.480469,if crooked hillary clinton can't close the dea...
1635,1635,2016-05-17 11:37:03+00:00,-0.6114,17701.460938,17469.919922,the pathetic new hit ad against me misrepresen...
1636,1636,2016-05-17 11:46:22+00:00,0.0000,17701.460938,17469.919922,crooked hillary clinton put out an ad where i ...
1699,1699,2016-05-20 09:47:09+00:00,0.7506,17571.750000,17437.320313,crooked hillary has zero imagination and even ...
...,...,...,...,...,...,...
24979,24979,2020-08-07 22:32:51+00:00,0.1513,27456.240234,27223.550781,i will be doing a news conference on the china...
25034,25034,2020-08-11 12:33:47+00:00,0.4003,28154.880859,27624.509766,"more testing, which is a good thing (we have t..."
25096,25096,2020-08-14 04:58:42+00:00,0.6932,27977.810547,27759.390625,rt @buds1008: @katiepavlich @lindasuhler let's...
25158,25158,2020-08-14 16:25:47+00:00,-0.2942,27977.810547,27759.390625,i am ready to have @ustreasury and @sba send a...
25164,25164,2020-08-14 19:02:33+00:00,-0.2942,27977.810547,27759.390625,i am ready to send rental assistance payments ...

In [41]:
tax_cuts = dataset[dataset['Tweet_text'].str.contains('tax cuts')]
tax_cuts

,Unnamed: 0,Time,Vader_compound,High,Low,Tweet_text
4483,4483,2017-03-30 21:18:57+00:00,0.4404,20753.779297,20643.599609,"if @repmarkmeadows, @jim_jordan and raul_labra..."
4484,4484,2017-03-30 21:20:44+00:00,0.4404,20753.779297,20643.599609,"if @repmarkmeadows, @jim_jordan and @raul_labr..."
4536,4536,2017-04-11 12:59:20+00:00,0.8519,20660.029297,20512.560547,ron estes is running today for congress in the...
4783,4783,2017-05-29 00:07:01+00:00,0.6468,21092.820313,21050.490234,the massive tax cuts/reform that i have submit...
4791,4791,2017-05-30 13:59:28+00:00,0.6333,21063.619141,21009.599609,"the u.s. senate should switch to 51 votes, imm..."
...,...,...,...,...,...,...
21361,21361,2020-04-21 16:49:12+00:00,0.6705,23365.250000,22941.880859,....to state/local governments for lost revenu...
21755,21755,2020-05-04 13:36:33+00:00,0.8703,23769.560547,23361.160156,"republicans love the biggest tax cuts, rebuilt..."
22421,22421,2020-05-22 23:12:27+00:00,0.8257,24481.640625,24294.070313,david young (@youngforiowa) is a champion for ...
23905,23905,2020-07-01 11:21:20+00:00,0.6369,26019.310547,25713.609375,rt @erictrump: biden: “i'm going to get rid of...
24378,24378,2020-07-19 02:56:51+00:00,0.2942,26808.429688,26619.880859,rt @gop: .@realdonaldtrump's tax cuts are work...

In [49]:
rally = dataset[dataset['Tweet_text'].str.contains('rally')]
rally

,Unnamed: 0,Time,Vader_compound,High,Low,Tweet_text
3,3,2016-01-20 15:53:12+00:00,0.8550,15989.450195,15450.559570,great rally in iowa! such wonderful people. tr...
84,84,2016-01-24 08:47:50+00:00,0.0000,16136.790039,15921.099609,"""@snoozinglion1: full speech: donald trump cam..."
86,86,2016-01-24 09:09:52+00:00,0.8481,16136.790039,15921.099609,"""@snoozinglion1: .@realdonaldtrump great comme..."
127,127,2016-01-26 04:27:32+00:00,0.0000,16185.790039,15893.160156,"""@jackburtonreflx: @jdenino1 @davidwohl @ss i..."
168,168,2016-01-28 04:26:38+00:00,0.0000,16102.139648,15863.719727,"""@creta_r: @realdonaldtrump looking forward to..."
...,...,...,...,...,...,...
23650,23650,2020-06-22 23:35:48+00:00,0.8725,26059.810547,25667.679688,wow! the trump rally gives @foxnews the “large...
24143,24143,2020-07-10 17:11:20+00:00,0.6476,26101.320313,25637.500000,with tropical storm fay heading towards the gr...
24431,24431,2020-07-23 12:19:09+00:00,0.3612,26973.849609,26560.039063,"rt @mzhemingway: fwiw, quite a few people in r..."
24753,24753,2020-08-01 18:57:24+00:00,0.9736,26440.019531,26013.589844,"jake, this wasn’t a trump rally, but rather a ..."
24846,24846,2020-08-03 11:27:29+00:00,0.4201,26707.259766,26534.380859,rt @teamtrump: president @realdonaldtrump from...

In [50]:
jobs = dataset[dataset['Tweet_text'].str.contains('jobs')]
jobs

,Unnamed: 0,Time,Vader_compound,High,Low,Tweet_text
315,315,2016-02-06 14:44:08+00:00,0.3331,16423.630859,16129.809570,"""@lisabrossman: @ukcatwoman52 @ericnlin @ac36..."
424,424,2016-02-13 15:16:43+00:00,0.0000,15974.040039,15691.620117,"now an additional 600-700 jobs in america (2,0..."
432,432,2016-02-13 17:01:59+00:00,0.0000,15974.040039,15691.620117,"""@grammies28: @realdonaldtrump was right! vote..."
439,439,2016-02-13 19:24:26+00:00,0.0000,15974.040039,15691.620117,"""@amfree: #trump on #ford, #carrier, shipping ..."
527,527,2016-02-19 21:00:59+00:00,0.7635,16410.960938,16278.000000,i have built so many great &amp; complicated p...
...,...,...,...,...,...,...
24982,24982,2020-08-08 00:31:50+00:00,0.0000,27456.240234,27223.550781,"rt @whitehouse: ""we added 1.8 million new jobs..."
25110,25110,2020-08-14 11:27:25+00:00,0.7430,27977.810547,27759.390625,rt @jepence: president trump promised to bring...
25117,25117,2020-08-14 11:30:02+00:00,-0.6962,27977.810547,27759.390625,rt @gopchairwoman: a biden-harris fracking ban...
25121,25121,2020-08-14 11:33:53+00:00,0.4588,27977.810547,27759.390625,rt @mike_pence: we’ve created more jobs in the...
25159,25159,2020-08-14 16:26:51+00:00,0.5255,27977.810547,27759.390625,i am ready to send more money to states and lo...